-- ==========================================
-- 创建 schedules 表（个人日程表）
-- ==========================================
-- 
-- 此脚本用于创建个人日程管理所需的 schedules 表
-- 执行方式：在 Supabase SQL Editor 中执行此脚本
-- ==========================================

-- 个人日程表
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL, -- pending, in_progress, completed, cancelled
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 状态约束
ALTER TABLE schedules DROP CONSTRAINT IF EXISTS valid_schedule_status;
ALTER TABLE schedules ADD CONSTRAINT valid_schedule_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'));

-- 启用 RLS
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- RLS 策略：用户只能查看、创建、更新、删除自己的日程
DROP POLICY IF EXISTS "Users can view their own schedules" ON schedules;
CREATE POLICY "Users can view their own schedules" ON schedules FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create their own schedules" ON schedules;
CREATE POLICY "Users can create their own schedules" ON schedules FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own schedules" ON schedules;
CREATE POLICY "Users can update their own schedules" ON schedules FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own schedules" ON schedules;
CREATE POLICY "Users can delete their own schedules" ON schedules FOR DELETE USING (auth.uid() = user_id);

-- 性能索引
CREATE INDEX IF NOT EXISTS idx_schedules_user_id ON schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_schedules_user_date_status ON schedules(user_id, date, status);

-- ==========================================
-- 完成
-- ==========================================
