-- ==========================================
-- ProjectFlow 团队项目管理系统 - 完整数据库配置
-- ==========================================
--
-- 版本: 2.5.0
-- 更新日期: 2026-02-05
--
-- 功能特性：
-- 1. 个人日程管理（支持日期范围和阶段性更新）
-- 2. 日程标签系统
-- 3. 团队协作和成员管理
-- 4. 任务管理和 WBS 工作分解
-- 5. 任务附件、依赖关系和工时记录
-- 6. 通知系统
-- 7. 审计日志
-- 8. 完整的权限控制（RLS）
--
-- 执行方式：
-- 在 Supabase SQL Editor 中直接执行全篇脚本
--
-- ==========================================

-- ==========================================
-- 第一部分：基础表结构（v2.0）
-- ==========================================

-- 1. 个人日程表（新版本：支持日期范围）
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,                    -- 计划启动日期
  end_date DATE,                               -- 计划完成日期（可选）
  description TEXT,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  priority VARCHAR(20) DEFAULT 'medium',       -- 优先级（新增v2.5）
  reminder_time TIMESTAMP WITH TIME ZONE,       -- 提醒时间（新增v2.5）
  reminder_type VARCHAR(20) DEFAULT 'app',     -- 提醒类型（新增v2.5）
  completion_notes TEXT,                       -- 完成备注（新增v2.5）
  deleted_at TIMESTAMP WITH TIME ZONE,         -- 软删除（新增v2.5）
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT valid_schedule_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  CONSTRAINT valid_schedule_priority CHECK (priority IN ('urgent', 'high', 'medium', 'low')),
  CONSTRAINT valid_reminder_type CHECK (reminder_type IN ('email', 'sms', 'app'))
);

-- 2. 日程更新记录表
CREATE TABLE IF NOT EXISTS schedule_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT REFERENCES schedules(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20),                          -- 更新时的状态（可选）
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT valid_update_status CHECK (status IS NULL OR status IN ('pending', 'in_progress', 'completed', 'cancelled'))
);

-- 3. 日程附件表
CREATE TABLE IF NOT EXISTS schedule_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  update_id BIGINT REFERENCES schedule_updates(id) ON DELETE CASCADE NOT NULL,
  file_name VARCHAR(500) NOT NULL,
  file_path TEXT NOT NULL,                     -- Supabase Storage 路径
  file_type VARCHAR(100),                      -- MIME type
  file_size BIGINT,                            -- 文件大小（字节）
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. 日程标签表（新增v2.5）
CREATE TABLE IF NOT EXISTS schedule_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT REFERENCES schedules(id) ON DELETE CASCADE NOT NULL,
  tag_name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(schedule_id, tag_name)
);

-- 5. 团队表
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. 团队成员表
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role VARCHAR(50) DEFAULT 'member' NOT NULL,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT valid_member_role CHECK (role IN ('owner', 'admin', 'member')),
  UNIQUE(team_id, user_id)
);

-- 7. 工作组表
CREATE TABLE IF NOT EXISTS work_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  leader_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. 工作组成员表
CREATE TABLE IF NOT EXISTS work_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(work_group_id, user_id)
);

-- 9. 任务表
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  priority VARCHAR(20) DEFAULT 'medium' NOT NULL,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  estimated_hours DECIMAL(5,2),                -- 预估工时（新增v2.5）
  actual_hours DECIMAL(5,2),                    -- 实际工时（新增v2.5）
  deleted_at TIMESTAMP WITH TIME ZONE,          -- 软删除（新增v2.5）

  CONSTRAINT valid_task_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  CONSTRAINT valid_task_priority CHECK (priority IN ('low', 'medium', 'high'))
);

-- 10. 工作子项表（WBS）
CREATE TABLE IF NOT EXISTS work_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  execution_order VARCHAR(20) NOT NULL,
  sequence_number INTEGER DEFAULT 0,
  planned_start_time TIMESTAMP WITH TIME ZONE,
  duration_hours DECIMAL(5,2),
  planned_end_time TIMESTAMP WITH TIME ZONE,
  assignee_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  collaborators JSONB DEFAULT '[]'::jsonb,
  objectives TEXT,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  progress INTEGER DEFAULT 0,
  actual_start_time TIMESTAMP WITH TIME ZONE,
  actual_end_time TIMESTAMP WITH TIME ZONE,
  blocked_reason TEXT,                         -- 阻塞原因（新增v2.5）
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT valid_work_item_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled', 'blocked')),
  CONSTRAINT valid_execution_order CHECK (execution_order IN ('parallel', 'sequential')),
  CONSTRAINT valid_progress CHECK (progress >= 0 AND progress <= 100)
);

-- 11. 工作子项状态历史表
CREATE TABLE IF NOT EXISTS work_item_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE NOT NULL,
  status VARCHAR(20) NOT NULL,
  progress INTEGER NOT NULL,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. 任务评论表
CREATE TABLE IF NOT EXISTS task_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT comment_target CHECK ((task_id IS NOT NULL AND work_item_id IS NULL) OR (task_id IS NULL AND work_item_id IS NOT NULL))
);

-- 13. 团队邀请表
CREATE TABLE IF NOT EXISTS team_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE NOT NULL,
  email VARCHAR(255) NOT NULL,
  invited_by UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  token VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  accepted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  CONSTRAINT valid_invitation_status CHECK (status IN ('pending', 'accepted', 'expired', 'cancelled'))
);

-- ==========================================
-- 第二部分：新增表结构（v2.4.0）
-- ==========================================

-- 14. 任务附件表（新增v2.4.0）
CREATE TABLE IF NOT EXISTS task_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
  file_name VARCHAR(500) NOT NULL,
  file_path TEXT NOT NULL,
  file_type VARCHAR(100),
  file_size BIGINT,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  uploaded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 15. 任务依赖关系表（新增v2.4.0）
CREATE TABLE IF NOT EXISTS task_dependencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
  depends_on_task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
  dependency_type VARCHAR(20) DEFAULT 'finish_to_start' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT task_no_self_dependency CHECK (task_id != depends_on_task_id),
  UNIQUE(task_id, depends_on_task_id)
);

-- 16. 通知表（新增v2.4.0）
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  related_type VARCHAR(50),
  related_id BIGINT,
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE
);

-- 17. 审计日志表（新增v2.4.0）
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id BIGINT NOT NULL,
  action VARCHAR(20) NOT NULL,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL NOT NULL,
  old_values JSONB,
  new_values JSONB,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 第三部分：索引优化
-- ==========================================

-- 个人日程索引
CREATE INDEX IF NOT EXISTS idx_schedules_user_id ON schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_schedules_start_date ON schedules(start_date);
CREATE INDEX IF NOT EXISTS idx_schedules_user_date_status ON schedules(user_id, start_date, status);
CREATE INDEX IF NOT EXISTS idx_schedules_priority ON schedules(priority);
CREATE INDEX IF NOT EXISTS idx_schedules_deleted ON schedules(deleted_at) WHERE deleted_at IS NULL;

-- 日程更新索引
CREATE INDEX IF NOT EXISTS idx_schedule_updates_schedule_id ON schedule_updates(schedule_id);
CREATE INDEX IF NOT EXISTS idx_schedule_updates_user_id ON schedule_updates(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_updates_created_at ON schedule_updates(created_at DESC);

-- 附件索引
CREATE INDEX IF NOT EXISTS idx_schedule_attachments_update_id ON schedule_attachments(update_id);

-- 日程标签索引
CREATE INDEX IF NOT EXISTS idx_schedule_tags_schedule_id ON schedule_tags(schedule_id);

-- 团队索引
CREATE INDEX IF NOT EXISTS idx_teams_owner_id ON teams(owner_id);

-- 团队成员索引
CREATE INDEX IF NOT EXISTS idx_team_members_team_id ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id ON team_members(user_id);

-- 工作组索引
CREATE INDEX IF NOT EXISTS idx_work_groups_team_id ON work_groups(team_id);
CREATE INDEX IF NOT EXISTS idx_work_group_members_group_id ON work_group_members(work_group_id);

-- 任务索引
CREATE INDEX IF NOT EXISTS idx_tasks_team_id ON tasks(team_id);
CREATE INDEX IF NOT EXISTS idx_tasks_created_by ON tasks(created_by);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
CREATE INDEX IF NOT EXISTS idx_tasks_hours ON tasks(estimated_hours, actual_hours);
CREATE INDEX IF NOT EXISTS idx_tasks_deleted ON tasks(deleted_at) WHERE deleted_at IS NULL;

-- 工作子项索引
CREATE INDEX IF NOT EXISTS idx_work_items_task_id ON work_items(task_id);
CREATE INDEX IF NOT EXISTS idx_work_items_assignee_id ON work_items(assignee_id);
CREATE INDEX IF NOT EXISTS idx_work_items_status ON work_items(status);

-- 评论索引
CREATE INDEX IF NOT EXISTS idx_task_comments_task_id ON task_comments(task_id);
CREATE INDEX IF NOT EXISTS idx_task_comments_work_item_id ON task_comments(work_item_id);

-- 邀请索引
CREATE INDEX IF NOT EXISTS idx_team_invitations_token ON team_invitations(token);
CREATE INDEX IF NOT EXISTS idx_team_invitations_email ON team_invitations(email);
CREATE INDEX IF NOT EXISTS idx_team_invitations_status ON team_invitations(status);

-- 任务附件索引
CREATE INDEX IF NOT EXISTS idx_task_attachments_task_id ON task_attachments(task_id);

-- 任务依赖索引
CREATE INDEX IF NOT EXISTS idx_task_dependencies_task_id ON task_dependencies(task_id);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_depends ON task_dependencies(depends_on_task_id);

-- 通知索引
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_expires ON notifications(user_id, expires_at) WHERE expires_at IS NOT NULL;

-- 审计日志索引
CREATE INDEX IF NOT EXISTS idx_audit_logs_record ON audit_logs(table_name, record_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(changed_by, changed_at DESC);

-- ==========================================
-- 第四部分：行级安全策略 (RLS)
-- ==========================================

-- 启用 RLS
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_item_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- RLS 辅助函数（避免 team_members 无限递归）
-- ==========================================

CREATE OR REPLACE FUNCTION public.is_team_member(check_team_id bigint, check_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.team_members
    WHERE team_id = check_team_id AND user_id = check_user_id
  );
$$;

CREATE OR REPLACE FUNCTION public.is_team_owner_or_admin(check_team_id bigint, check_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.team_members
    WHERE team_id = check_team_id AND user_id = check_user_id AND role IN ('owner', 'admin')
  );
$$;

CREATE OR REPLACE FUNCTION public.get_team_owner_id(check_team_id bigint)
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT owner_id FROM public.teams WHERE id = check_team_id LIMIT 1;
$$;

-- ========== 个人日程策略 ==========

DROP POLICY IF EXISTS "Users can view their own schedules" ON schedules;
CREATE POLICY "Users can view their own schedules"
  ON schedules FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create their own schedules" ON schedules;
CREATE POLICY "Users can create their own schedules"
  ON schedules FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own schedules" ON schedules;
CREATE POLICY "Users can update their own schedules"
  ON schedules FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own schedules" ON schedules;
CREATE POLICY "Users can delete their own schedules"
  ON schedules FOR DELETE
  USING (auth.uid() = user_id);

-- ========== 日程更新策略 ==========

DROP POLICY IF EXISTS "Users can view updates for their schedules" ON schedule_updates;
CREATE POLICY "Users can view updates for their schedules"
  ON schedule_updates FOR SELECT
  USING (
    auth.uid() = user_id
    OR
    EXISTS (
      SELECT 1 FROM schedules
      WHERE schedules.id = schedule_updates.schedule_id
      AND schedules.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can create updates for their schedules" ON schedule_updates;
CREATE POLICY "Users can create updates for their schedules"
  ON schedule_updates FOR INSERT
  WITH CHECK (
    auth.uid() = user_id
    AND
    EXISTS (
      SELECT 1 FROM schedules
      WHERE schedules.id = schedule_updates.schedule_id
      AND schedules.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can update their own updates" ON schedule_updates;
CREATE POLICY "Users can update their own updates"
  ON schedule_updates FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own updates" ON schedule_updates;
CREATE POLICY "Users can delete their own updates"
  ON schedule_updates FOR DELETE
  USING (auth.uid() = user_id);

-- ========== 附件策略 ==========

DROP POLICY IF EXISTS "Users can view attachments for their updates" ON schedule_attachments;
CREATE POLICY "Users can view attachments for their updates"
  ON schedule_attachments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM schedule_updates
      WHERE schedule_updates.id = schedule_attachments.update_id
      AND schedule_updates.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can create attachments for their updates" ON schedule_attachments;
CREATE POLICY "Users can create attachments for their updates"
  ON schedule_attachments FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM schedule_updates
      WHERE schedule_updates.id = schedule_attachments.update_id
      AND schedule_updates.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can delete their own attachments" ON schedule_attachments;
CREATE POLICY "Users can delete their own attachments"
  ON schedule_attachments FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM schedule_updates
      WHERE schedule_updates.id = schedule_attachments.update_id
      AND schedule_updates.user_id = auth.uid()
    )
  );

-- ========== 日程标签策略 ==========

DROP POLICY IF EXISTS "Users can view their own schedule tags" ON schedule_tags;
CREATE POLICY "Users can view their own schedule tags"
  ON schedule_tags FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM schedules
      WHERE schedules.id = schedule_tags.schedule_id
      AND schedules.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can create tags for their schedules" ON schedule_tags;
CREATE POLICY "Users can create tags for their schedules"
  ON schedule_tags FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM schedules
      WHERE schedules.id = schedule_tags.schedule_id
      AND schedules.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can delete their own schedule tags" ON schedule_tags;
CREATE POLICY "Users can delete their own schedule tags"
  ON schedule_tags FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM schedules
      WHERE schedules.id = schedule_tags.schedule_id
      AND schedules.user_id = auth.uid()
    )
  );

-- ========== 团队策略（使用辅助函数，避免无限递归） ==========

DROP POLICY IF EXISTS "Team members can view their teams" ON teams;
CREATE POLICY "Team members can view their teams"
  ON teams FOR SELECT
  USING (
    is_team_member(id, auth.uid()) OR owner_id = auth.uid()
  );

DROP POLICY IF EXISTS "Users can create teams" ON teams;
CREATE POLICY "Users can create teams"
  ON teams FOR INSERT
  WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Team owners can update their teams" ON teams;
CREATE POLICY "Team owners can update their teams"
  ON teams FOR UPDATE
  USING (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Team owners can delete their teams" ON teams;
CREATE POLICY "Team owners can delete their teams"
  ON teams FOR DELETE
  USING (auth.uid() = owner_id);

-- ========== 团队成员策略（使用辅助函数，避免无限递归） ==========

DROP POLICY IF EXISTS "Team members can view team membership" ON team_members;
CREATE POLICY "Team members can view team membership"
  ON team_members FOR SELECT
  USING (is_team_member(team_id, auth.uid()));

DROP POLICY IF EXISTS "Team owners and admins can add members" ON team_members;
CREATE POLICY "Team owners and admins can add members"
  ON team_members FOR INSERT
  WITH CHECK (
    (user_id = auth.uid() AND (is_team_owner_or_admin(team_id, auth.uid()) OR get_team_owner_id(team_id) = auth.uid()))
    OR is_team_owner_or_admin(team_id, auth.uid())
  );

DROP POLICY IF EXISTS "Team owners and admins can update members" ON team_members;
CREATE POLICY "Team owners and admins can update members"
  ON team_members FOR UPDATE
  USING (is_team_owner_or_admin(team_id, auth.uid()));

DROP POLICY IF EXISTS "Team owners and admins can remove members" ON team_members;
CREATE POLICY "Team owners and admins can remove members"
  ON team_members FOR DELETE
  USING (is_team_owner_or_admin(team_id, auth.uid()));

-- ========== 工作组策略 ==========

DROP POLICY IF EXISTS "Team members can view work groups" ON work_groups;
CREATE POLICY "Team members can view work groups"
  ON work_groups FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = work_groups.team_id
      AND team_members.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team owners and admins can manage work groups" ON work_groups;
CREATE POLICY "Team owners and admins can manage work groups"
  ON work_groups FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = work_groups.team_id
      AND team_members.user_id = auth.uid()
      AND team_members.role IN ('owner', 'admin')
    )
  );

-- ========== 工作组成员策略 ==========

DROP POLICY IF EXISTS "Team members can view work group membership" ON work_group_members;
CREATE POLICY "Team members can view work group membership"
  ON work_group_members FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM work_groups wg
      JOIN team_members tm ON tm.team_id = wg.team_id
      WHERE wg.id = work_group_members.work_group_id
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team owners and admins can manage work group members" ON work_group_members;
CREATE POLICY "Team owners and admins can manage work group members"
  ON work_group_members FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM work_groups wg
      JOIN team_members tm ON tm.team_id = wg.team_id
      WHERE wg.id = work_group_members.work_group_id
      AND tm.user_id = auth.uid()
      AND tm.role IN ('owner', 'admin')
    )
  );

-- ========== 任务策略 ==========

DROP POLICY IF EXISTS "Team members can view tasks" ON tasks;
CREATE POLICY "Team members can view tasks"
  ON tasks FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = tasks.team_id
      AND team_members.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can create tasks" ON tasks;
CREATE POLICY "Team members can create tasks"
  ON tasks FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = tasks.team_id
      AND team_members.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can update tasks" ON tasks;
CREATE POLICY "Team members can update tasks"
  ON tasks FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = tasks.team_id
      AND team_members.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team owners and admins can delete tasks" ON tasks;
CREATE POLICY "Team owners and admins can delete tasks"
  ON tasks FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = tasks.team_id
      AND team_members.user_id = auth.uid()
      AND team_members.role IN ('owner', 'admin')
    )
  );

-- ========== 工作子项策略 ==========

DROP POLICY IF EXISTS "Team members can view work items" ON work_items;
CREATE POLICY "Team members can view work items"
  ON work_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = work_items.task_id
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can manage work items" ON work_items;
CREATE POLICY "Team members can manage work items"
  ON work_items FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = work_items.task_id
      AND tm.user_id = auth.uid()
    )
  );

-- ========== 状态历史策略 ==========

DROP POLICY IF EXISTS "Team members can view status history" ON work_item_status_history;
CREATE POLICY "Team members can view status history"
  ON work_item_status_history FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM work_items wi
      JOIN tasks t ON t.id = wi.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE wi.id = work_item_status_history.work_item_id
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can create status history" ON work_item_status_history;
CREATE POLICY "Team members can create status history"
  ON work_item_status_history FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM work_items wi
      JOIN tasks t ON t.id = wi.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE wi.id = work_item_status_history.work_item_id
      AND tm.user_id = auth.uid()
    )
  );

-- ========== 评论策略 ==========

DROP POLICY IF EXISTS "Team members can view comments" ON task_comments;
CREATE POLICY "Team members can view comments"
  ON task_comments FOR SELECT
  USING (
    (task_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_comments.task_id
      AND tm.user_id = auth.uid()
    ))
    OR
    (work_item_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM work_items wi
      JOIN tasks t ON t.id = wi.task_id
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE wi.id = task_comments.work_item_id
      AND tm.user_id = auth.uid()
    ))
  );

DROP POLICY IF EXISTS "Team members can create comments" ON task_comments;
CREATE POLICY "Team members can create comments"
  ON task_comments FOR INSERT
  WITH CHECK (
    auth.uid() = user_id
    AND
    (
      (task_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM tasks t
        JOIN team_members tm ON tm.team_id = t.team_id
        WHERE t.id = task_comments.task_id
        AND tm.user_id = auth.uid()
      ))
      OR
      (work_item_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM work_items wi
        JOIN tasks t ON t.id = wi.task_id
        JOIN team_members tm ON tm.team_id = t.team_id
        WHERE wi.id = task_comments.work_item_id
        AND tm.user_id = auth.uid()
      ))
    )
  );

DROP POLICY IF EXISTS "Users can delete their own comments" ON task_comments;
CREATE POLICY "Users can delete their own comments"
  ON task_comments FOR DELETE
  USING (auth.uid() = user_id);

-- ========== 邀请策略 ==========

DROP POLICY IF EXISTS "Team owners and admins can view invitations" ON team_invitations;
CREATE POLICY "Team owners and admins can view invitations"
  ON team_invitations FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = team_invitations.team_id
      AND team_members.user_id = auth.uid()
      AND team_members.role IN ('owner', 'admin')
    )
  );

DROP POLICY IF EXISTS "Team owners and admins can create invitations" ON team_invitations;
CREATE POLICY "Team owners and admins can create invitations"
  ON team_invitations FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = team_invitations.team_id
      AND team_members.user_id = auth.uid()
      AND team_members.role IN ('owner', 'admin')
    )
  );

DROP POLICY IF EXISTS "Team owners and admins can update invitations" ON team_invitations;
CREATE POLICY "Team owners and admins can update invitations"
  ON team_invitations FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM team_members
      WHERE team_members.team_id = team_invitations.team_id
      AND team_members.user_id = auth.uid()
      AND team_members.role IN ('owner', 'admin')
    )
  );

-- ========== 任务附件策略 ==========

DROP POLICY IF EXISTS "Team members can view task attachments" ON task_attachments;
CREATE POLICY "Team members can view task attachments"
  ON task_attachments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_attachments.task_id
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can create task attachments" ON task_attachments;
CREATE POLICY "Team members can create task attachments"
  ON task_attachments FOR INSERT
  WITH CHECK (
    auth.uid() = uploaded_by
    AND EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_attachments.task_id
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can delete their own task attachments" ON task_attachments;
CREATE POLICY "Team members can delete their own task attachments"
  ON task_attachments FOR DELETE
  USING (auth.uid() = uploaded_by);

-- ========== 任务依赖策略 ==========

DROP POLICY IF EXISTS "Team members can view task dependencies" ON task_dependencies;
CREATE POLICY "Team members can view task dependencies"
  ON task_dependencies FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE (t.id = task_dependencies.task_id OR t.id = task_dependencies.depends_on_task_id)
      AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Team members can manage task dependencies" ON task_dependencies;
CREATE POLICY "Team members can manage task dependencies"
  ON task_dependencies FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = task_dependencies.task_id
      AND tm.user_id = auth.uid()
    )
  );

-- ========== 通知策略 ==========

DROP POLICY IF EXISTS "Users can view their own notifications" ON notifications;
CREATE POLICY "Users can view their own notifications"
  ON notifications FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications"
  ON notifications FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "System can create notifications" ON notifications;
CREATE POLICY "System can create notifications"
  ON notifications FOR INSERT
  WITH CHECK (true); -- Edge Functions 或系统可插入

-- ========== 审计日志策略 ==========

DROP POLICY IF EXISTS "Users can view audit logs for their team" ON audit_logs;
CREATE POLICY "Users can view audit logs for their team"
  ON audit_logs FOR SELECT
  USING (
    -- 日程相关审计
    (table_name = 'schedules' AND EXISTS (
      SELECT 1 FROM schedules s
      WHERE s.id = audit_logs.record_id
      AND s.user_id = auth.uid()
    ))
    OR
    -- 团队相关审计（需通过tasks/work_items间接验证）
    (table_name = 'tasks' AND EXISTS (
      SELECT 1 FROM tasks t
      JOIN team_members tm ON tm.team_id = t.team_id
      WHERE t.id = audit_logs.record_id
      AND tm.user_id = auth.uid()
    ))
  );

DROP POLICY IF EXISTS "System can create audit logs" ON audit_logs;
CREATE POLICY "System can create audit logs"
  ON audit_logs FOR INSERT
  WITH CHECK (true); -- 系统可插入

-- ==========================================
-- 第五部分：表注释
-- ==========================================

COMMENT ON TABLE schedules IS '个人日程表：支持日期范围、优先级、提醒和阶段性更新';
COMMENT ON TABLE schedule_updates IS '日程更新记录表：存储日程的阶段性进展';
COMMENT ON TABLE schedule_attachments IS '日程附件表：存储更新记录的附件信息';
COMMENT ON TABLE schedule_tags IS '日程标签表：支持多标签管理';
COMMENT ON TABLE teams IS '团队表：组织协作的基础单位';
COMMENT ON TABLE team_members IS '团队成员表：管理团队成员和角色';
COMMENT ON TABLE work_groups IS '工作组表：团队内的小组划分';
COMMENT ON TABLE work_group_members IS '工作组成员表：管理工作组成员';
COMMENT ON TABLE tasks IS '任务表：团队的主要工作任务';
COMMENT ON TABLE work_items IS '工作子项表：任务的WBS分解';
COMMENT ON TABLE work_item_status_history IS '工作子项状态历史表：记录状态变更历史';
COMMENT ON TABLE task_comments IS '任务评论表：任务和工作子项的讨论';
COMMENT ON TABLE team_invitations IS '团队邀请表：邮箱邀请机制';
COMMENT ON TABLE task_attachments IS '任务附件表：存储任务级别的文件附件';
COMMENT ON TABLE task_dependencies IS '任务依赖关系表：管理任务间的依赖关系';
COMMENT ON TABLE notifications IS '通知表：统一的通知管理系统';
COMMENT ON TABLE audit_logs IS '审计日志表：记录所有数据变更历史';

-- ==========================================
-- 完成
-- ==========================================

-- 验证表创建
SELECT
  table_name,
  pg_size_pretty(pg_total_relation_size(quote_ident(table_name)::regclass)) as size
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;
