-- ==========================================
-- ProjectFlow 团队项目管理系统 - 完整数据库配置脚本 (v2.2.0)
-- ==========================================
-- 
-- 版本说明：
-- 1. 包含完整表结构、约束、触发器
-- 2. 彻底解决 RLS 递归问题，并恢复成员访问权限
-- 3. 包含高性能索引优化
-- 4. 包含完善的团队邮箱邀请功能
-- 
-- 执行方式：
-- 在 Supabase SQL Editor 中直接执行全篇脚本即可。
-- ==========================================

-- ==========================================
-- 1. 基础表结构创建
-- ==========================================

-- 个人日程表
CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL, -- pending, in_progress, completed, cancelled
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 团队表
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 团队成员表
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role VARCHAR(50) DEFAULT 'member', -- owner, admin, member
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(team_id, user_id)
);

-- 工作组表
CREATE TABLE IF NOT EXISTS work_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  leader_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作组成员表
CREATE TABLE IF NOT EXISTS work_group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(work_group_id, user_id)
);

-- 任务表
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  work_group_id BIGINT REFERENCES work_groups(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  status VARCHAR(20) DEFAULT 'pending', -- pending, in_progress, completed, cancelled
  priority VARCHAR(20) DEFAULT 'medium', -- low, medium, high
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作子项表
CREATE TABLE IF NOT EXISTS work_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  execution_order VARCHAR(20) NOT NULL, -- parallel, sequential
  sequence_number INTEGER DEFAULT 0,
  planned_start_time TIMESTAMP WITH TIME ZONE,
  duration_hours DECIMAL(5,2),
  planned_end_time TIMESTAMP WITH TIME ZONE,
  assignee_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  collaborators JSONB DEFAULT '[]'::jsonb,
  objectives TEXT,
  status VARCHAR(20) DEFAULT 'pending', -- pending, in_progress, completed, cancelled, blocked
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  actual_start_time TIMESTAMP WITH TIME ZONE,
  actual_end_time TIMESTAMP WITH TIME ZONE,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 工作子项状态历史表
CREATE TABLE IF NOT EXISTS work_item_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL,
  progress INTEGER DEFAULT 0,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 任务/子项评论表
CREATE TABLE IF NOT EXISTS task_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES tasks(id) ON DELETE CASCADE,
  work_item_id BIGINT REFERENCES work_items(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 团队邀请表
CREATE TABLE IF NOT EXISTS team_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  invited_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  token VARCHAR(255) NOT NULL UNIQUE,
  status VARCHAR(20) DEFAULT 'pending', -- pending, accepted, expired, cancelled
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  accepted_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(team_id, email, status)
);

-- ==========================================
-- 2. 约束与触发器
-- ==========================================

-- 状态约束
ALTER TABLE schedules DROP CONSTRAINT IF EXISTS valid_schedule_status;
ALTER TABLE schedules ADD CONSTRAINT valid_schedule_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'));

ALTER TABLE team_members DROP CONSTRAINT IF EXISTS valid_member_role;
ALTER TABLE team_members ADD CONSTRAINT valid_member_role CHECK (role IN ('owner', 'admin', 'member'));

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS valid_task_status;
ALTER TABLE tasks ADD CONSTRAINT valid_task_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'));

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS valid_task_priority;
ALTER TABLE tasks ADD CONSTRAINT valid_task_priority CHECK (priority IN ('low', 'medium', 'high'));

ALTER TABLE work_items DROP CONSTRAINT IF EXISTS valid_work_item_status;
ALTER TABLE work_items ADD CONSTRAINT valid_work_item_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled', 'blocked'));

ALTER TABLE team_invitations DROP CONSTRAINT IF EXISTS valid_invitation_status;
ALTER TABLE team_invitations ADD CONSTRAINT valid_invitation_status CHECK (status IN ('pending', 'accepted', 'expired', 'cancelled'));

-- 自动更新 updated_at 触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;
CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_work_items_updated_at ON work_items;
CREATE TRIGGER update_work_items_updated_at BEFORE UPDATE ON work_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 3. 安全辅助函数 (SECURITY DEFINER)
-- ==========================================

-- 检查团队成员身份 (打破 RLS 递归的关键)
CREATE OR REPLACE FUNCTION public.is_team_member(p_team_id bigint)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM team_members
    WHERE team_id = p_team_id
    AND user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 检查团队所有者身份
CREATE OR REPLACE FUNCTION public.is_team_owner(p_team_id bigint)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM teams
    WHERE id = p_team_id
    AND owner_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 生成邀请令牌
CREATE OR REPLACE FUNCTION generate_invitation_token()
RETURNS TEXT AS $$
BEGIN
  RETURN gen_random_uuid()::TEXT;
END;
$$ LANGUAGE plpgsql;

-- 创建团队邀请
CREATE OR REPLACE FUNCTION create_team_invitation(
  p_team_id BIGINT,
  p_email VARCHAR(255),
  p_invited_by UUID
)
RETURNS TABLE (id BIGINT, token VARCHAR(255), expires_at TIMESTAMP WITH TIME ZONE) AS $$
DECLARE
  v_token VARCHAR(255);
  v_expires_at TIMESTAMP WITH TIME ZONE;
  v_invitation_id BIGINT;
BEGIN
  PERFORM set_config('row_security', 'off', true);
  IF EXISTS (SELECT 1 FROM team_invitations WHERE team_id = p_team_id AND email = p_email AND status = 'pending' AND team_invitations.expires_at > NOW()) THEN
    RAISE EXCEPTION '该邮箱已有待处理的邀请';
  END IF;
  v_token := generate_invitation_token();
  v_expires_at := NOW() + INTERVAL '7 days';
  INSERT INTO team_invitations (team_id, email, invited_by, token, expires_at)
  VALUES (p_team_id, p_email, p_invited_by, v_token, v_expires_at)
  RETURNING team_invitations.id, team_invitations.token, team_invitations.expires_at INTO v_invitation_id, v_token, v_expires_at;
  id := v_invitation_id; token := v_token; expires_at := v_expires_at;
  RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 接受团队邀请
CREATE OR REPLACE FUNCTION accept_team_invitation(p_token VARCHAR(255), p_user_id UUID)
RETURNS TABLE (team_id BIGINT, success BOOLEAN) AS $$
DECLARE
  v_invitation RECORD;
  v_user_email VARCHAR(255);
BEGIN
  PERFORM set_config('row_security', 'off', true);
  SELECT * INTO v_invitation FROM team_invitations WHERE team_invitations.token = p_token AND status = 'pending' AND team_invitations.expires_at > NOW();
  IF NOT FOUND THEN RAISE EXCEPTION '邀请不存在或已过期'; END IF;
  SELECT auth.users.email INTO v_user_email FROM auth.users WHERE auth.users.id = p_user_id;
  IF v_user_email != v_invitation.email THEN RAISE EXCEPTION '邮箱不匹配'; END IF;
  INSERT INTO team_members (team_id, user_id, role) VALUES (v_invitation.team_id, p_user_id, 'member') ON CONFLICT (team_id, user_id) DO NOTHING;
  UPDATE team_invitations SET status = 'accepted', accepted_at = NOW() WHERE team_invitations.id = v_invitation.id;
  team_id := v_invitation.team_id; success := TRUE;
  RETURN NEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 4. RLS 行级安全策略配置
-- ==========================================

-- 启用 RLS
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_item_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_invitations ENABLE ROW LEVEL SECURITY;

-- schedules 策略（个人日程）
DROP POLICY IF EXISTS "Users can view their own schedules" ON schedules;
CREATE POLICY "Users can view their own schedules" ON schedules FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can create their own schedules" ON schedules;
CREATE POLICY "Users can create their own schedules" ON schedules FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update their own schedules" ON schedules;
CREATE POLICY "Users can update their own schedules" ON schedules FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete their own schedules" ON schedules;
CREATE POLICY "Users can delete their own schedules" ON schedules FOR DELETE USING (auth.uid() = user_id);

-- teams 策略
DROP POLICY IF EXISTS "Team members can view their team" ON teams;
CREATE POLICY "Team members can view their team" ON teams FOR SELECT USING (is_team_member(id) OR owner_id = auth.uid());
DROP POLICY IF EXISTS "Users can create teams" ON teams;
CREATE POLICY "Users can create teams" ON teams FOR INSERT WITH CHECK (auth.uid() = owner_id);
DROP POLICY IF EXISTS "Team owners can update team" ON teams;
CREATE POLICY "Team owners can update team" ON teams FOR UPDATE USING (owner_id = auth.uid());
DROP POLICY IF EXISTS "Only owner can delete team" ON teams;
CREATE POLICY "Only owner can delete team" ON teams FOR DELETE USING (owner_id = auth.uid());

-- team_members 策略
DROP POLICY IF EXISTS "Team members can view members" ON team_members;
CREATE POLICY "Team members can view members" ON team_members FOR SELECT USING (is_team_member(team_id));
DROP POLICY IF EXISTS "Owners can add members" ON team_members;
CREATE POLICY "Owners can add members" ON team_members FOR INSERT WITH CHECK (is_team_owner(team_id));
DROP POLICY IF EXISTS "Owners can update members" ON team_members;
CREATE POLICY "Owners can update members" ON team_members FOR UPDATE USING (is_team_owner(team_id));
DROP POLICY IF EXISTS "Only owners can remove members" ON team_members;
CREATE POLICY "Only owners can remove members" ON team_members FOR DELETE USING (is_team_owner(team_id));

-- tasks 策略
DROP POLICY IF EXISTS "Team members can view tasks" ON tasks;
CREATE POLICY "Team members can view tasks" ON tasks FOR SELECT USING (is_team_member(team_id));
DROP POLICY IF EXISTS "Team members can create tasks" ON tasks;
CREATE POLICY "Team members can create tasks" ON tasks FOR INSERT WITH CHECK (is_team_member(team_id) AND created_by = auth.uid());
DROP POLICY IF EXISTS "Team members can update tasks" ON tasks;
CREATE POLICY "Team members can update tasks" ON tasks FOR UPDATE USING (is_team_member(team_id));

-- team_invitations 策略
DROP POLICY IF EXISTS "Team owners can view invitations" ON team_invitations;
CREATE POLICY "Team owners can view invitations" ON team_invitations FOR SELECT USING (is_team_owner(team_id));
DROP POLICY IF EXISTS "Team owners can update invitations" ON team_invitations;
CREATE POLICY "Team owners can update invitations" ON team_invitations FOR UPDATE USING (is_team_owner(team_id));

-- 其他基础策略 (WorkGroups, WorkItems, Comments)
DROP POLICY IF EXISTS "Team members view work groups" ON work_groups;
CREATE POLICY "Team members view work groups" ON work_groups FOR SELECT USING (is_team_member(team_id));
DROP POLICY IF EXISTS "Team members view work items" ON work_items;
CREATE POLICY "Team members view work items" ON work_items FOR SELECT USING (EXISTS (SELECT 1 FROM tasks WHERE id = task_id AND is_team_member(team_id)));
DROP POLICY IF EXISTS "Team members view comments" ON task_comments;
CREATE POLICY "Team members view comments" ON task_comments FOR SELECT USING ((task_id IS NOT NULL AND EXISTS (SELECT 1 FROM tasks WHERE id = task_id AND is_team_member(team_id))) OR (work_item_id IS NOT NULL AND EXISTS (SELECT 1 FROM work_items WHERE id = work_item_id AND EXISTS (SELECT 1 FROM tasks WHERE id = task_id AND is_team_member(team_id)))));

-- ==========================================
-- 5. 高性能索引
-- ==========================================

-- 基础外键索引
CREATE INDEX IF NOT EXISTS idx_schedules_user_id ON schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_schedules_user_date_status ON schedules(user_id, date, status);
CREATE INDEX IF NOT EXISTS idx_teams_owner ON teams(owner_id);
CREATE INDEX IF NOT EXISTS idx_team_members_team ON team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_work_groups_team ON work_groups(team_id);
CREATE INDEX IF NOT EXISTS idx_tasks_team ON tasks(team_id);
CREATE INDEX IF NOT EXISTS idx_work_items_task ON work_items(task_id);

-- 性能优化复合索引 (v2.2.0 新增)
CREATE INDEX IF NOT EXISTS idx_work_group_members_user ON work_group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_group_status ON tasks(work_group_id, status);
CREATE INDEX IF NOT EXISTS idx_work_items_assignee_status ON work_items(assignee_id, status);
CREATE INDEX IF NOT EXISTS idx_work_items_planned_start ON work_items(planned_start_time);
CREATE INDEX IF NOT EXISTS idx_team_invitations_email_status ON team_invitations(email, status);
CREATE INDEX IF NOT EXISTS idx_work_item_history_composite ON work_item_status_history(work_item_id, changed_at);

-- ==========================================
-- 完成
-- ==========================================
